configs:
  - name: "all"
    preText: |
      Below is the file and directory structure of asker.
    output: "clipboard" # "file" or "clipboard"
    targets:
      include:
        - "src"
        - "bin"
        - "./"
      exclude:
        - "**/node_modules"
        - "dist"
        - "asker-asker.md"
      filePatterns:
        - "**/*.ts"
        - "**/*.js"
        - "**/*.yaml"
        - "**/*.json"
        - "*.md"
    tree:
      maxDepth: 5
      directoriesOnly: false

  - name: "ask ai"
    preText: |
      Here is the file and directory structure of asker. Read it carefully and answer user's question placed at the end.
    postText: |
      Question:
    output: "clipboard" # クリップボードにコピーする
    targets:
      include:
        - "apps/www"
      exclude:
        - "apps/www/node_modules"
      filePatterns:
        - "**/*.vue"
        - "**/*.js"
        - "**/*.ts"
    tree:
      maxDepth: 10
      directoriesOnly: false
