configs:
  - name: "asker"
    preText: |
      以下はaskerのファイルとディレクトリ構造の一覧です。
    targets:
      include:
        - "src"
        - "bin"
        - "./"
      exclude:
        - "**/node_modules"
        - "dist"
      filePatterns:
        - "**/*.ts"
        - "**/*.js"
        - "**/*.yaml"
        - "**/*.json"
        - "readme.md"
    tree:
      maxDepth: 5
      directoriesOnly: false

  - name: "review"
    preText: |
      こちらは "review" 設定用です。
    postText: |
      以上が "review" 設定の出力です。
    targets:
      include:
        - "apps/www"
      exclude:
        - "apps/www/node_modules"
      filePatterns:
        - "**/*.vue"
        - "**/*.js"
        - "**/*.ts"
    tree:
      maxDepth: 10
      directoriesOnly: false
